#!/bin/bash
# Sources:
#    http://www.fredshack.com/docs/linksys_3102.html
#    http://forums.digium.com/viewtopic.php?t=72277
#    http://forum.voxilla.com/threads/starter-spa3102-asterisk-setup.9352/

calc_wt_size() {
    # NOTE: it's tempting to redirect stderr to /dev/null, so supress error 
    # output from tput. However in this case, tput detects neither stdout or 
    # stderr is a tty and so only gives default 80, 24 values
    WT_HEIGHT=17
    WT_WIDTH=$(tput cols)

    if [ -z "$WT_WIDTH" ] || [ "$WT_WIDTH" -lt 60 ]; then
        WT_WIDTH=80
    fi
    if [ "$WT_WIDTH" -gt 178 ]; then
        WT_WIDTH=120
    fi
    WT_MENU_HEIGHT=$(($WT_HEIGHT-7))
}

function is_valid_ip()
{
    local  ip=$1
    local  stat=1

    if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        OIFS=$IFS
        IFS='.'
        ip=($ip)
        IFS=$OIFS
        [[ ${ip[0]} -le 255 && ${ip[1]} -le 255 \
            && ${ip[2]} -le 255 && ${ip[3]} -le 255 ]]
        stat=$?
    fi
    return $stat
}

do_spa3102_config() {
    local SPA3102_IP_ADDRESS
    local SPA3102_PSTN_CID
    local SPA3102_PSTN_USERNAME='PSTN'
    local SPA3102_PSTN_PASSWD
    local SPA3102_PSTN_SIP_PORT='5061'
    
    local SPA3102_LINE1_USERNAME
    local SPA3102_LINE1_PASSWD
    local SPA3102_LINE1_SIP_PORT='5062'
    
    local SPA3102_NAT='no'
    
    # my area uses 9 digit dialing, hence the 9 X's
    # change the following line to suit your needs
    local AREA_DIAL_PLAN='_XXXXXXXXX'
    
    if [ ! -f /etc/asterisk/sip.conf.orig ]; then
        cp /etc/asterisk/sip.conf /etc/asterisk/sip.conf.orig
    fi
    
    while true; do
        SPA3102_IP_ADDRESS=$(whiptail --inputbox "Please enter the IP Address of SPA3102" 20 60 "" 3>&1 1>&2 2>&3)
        if [ $? -eq 0 ]; then
            if is_valid_ip $SPA3102_IP_ADDRESS; then
                break
            else
                whiptail --msgbox "Invalid IP address." 20 60 1
            fi
        else
            return 1
        fi
    done
    
    whiptail --yesno "SPA3102 is behind NAT?" 20 60 2
    if [ $? -eq 0 ]; then # yes
        SPA3102_NAT='yes'
    fi
    
    SPA3102_PSTN_SIP_PORT=$(whiptail --inputbox "Please enter the SIP port of SPA3102 PSTN" 20 60 "${SPA3102_PSTN_SIP_PORT}" 3>&1 1>&2 2>&3)
    if [ $? -ne 0 ]; then
        return 1
    fi
    
    SPA3102_PSTN_CID=$(whiptail --inputbox "Please enter the phone number of SPA3102 PSTN" 20 60 "" 3>&1 1>&2 2>&3)
    if [ $? -ne 0 ]; then
        return 1
    fi
    
    SPA3102_PSTN_USERNAME=$(whiptail --inputbox "Please enter the username of SPA3102 PSTN" 20 60 "${SPA3102_PSTN_USERNAME}" 3>&1 1>&2 2>&3)
    if [ $? -ne 0 ]; then
        return 1
    fi
    
    SPA3102_PSTN_PASSWD=$(whiptail --passwordbox "Please enter the password of SPA3102 PSTN" 20 60 "" 3>&1 1>&2 2>&3)
    if [ $? -ne 0 ]; then
        return 1
    fi
    
    # Line 1
    SPA3102_LINE1_SIP_PORT=$(whiptail --inputbox "Please enter the SIP port of SPA3102 Line1" 20 60 "${SPA3102_LINE1_SIP_PORT}" 3>&1 1>&2 2>&3)
    if [ $? -ne 0 ]; then
        return 1
    fi
    
    SPA3102_LINE1_USERNAME=${SPA3102_PSTN_CID}
    SPA3102_LINE1_USERNAME=$(whiptail --inputbox "Please enter the username of SPA3102 Line1" 20 60 "${SPA3102_LINE1_USERNAME}" 3>&1 1>&2 2>&3)
    if [ $? -ne 0 ]; then
        return 1
    fi
    
    SPA3102_LINE1_PASSWD=$(whiptail --passwordbox "Please enter the password of SPA3102 Line1" 20 60 "" 3>&1 1>&2 2>&3)
    if [ $? -ne 0 ]; then
        return 1
    fi
    
    # Dial Plans
    AREA_DIAL_PLAN=$(whiptail --inputbox "Area dial plan" 20 60 "${AREA_DIAL_PLAN}" 3>&1 1>&2 2>&3)
    if [ $? -ne 0 ]; then
        return 1
    fi
    
    echo "" >> /etc/asterisk/sip.conf
    echo "[spa3102-line1]" >> /etc/asterisk/sip.conf
    echo "host=${SPA3102_IP_ADDRESS}" >> /etc/asterisk/sip.conf
    echo "port=${SPA3102_LINE1_SIP_PORT}" >> /etc/asterisk/sip.conf
    echo "username=${SPA3102_LINE1_USERNAME}" >> /etc/asterisk/sip.conf
    echo "secret=${SPA3102_LINE1_PASSWD}" >> /etc/asterisk/sip.conf
    echo "call-limit=1" >> /etc/asterisk/sip.conf
    echo "type=peer" >> /etc/asterisk/sip.conf
    echo "registersip=no" >> /etc/asterisk/sip.conf
    echo "context=spa3102-line1 ; the internal context controls what we can do" >> /etc/asterisk/sip.conf
    echo "hasvoicemail=no" >> /etc/asterisk/sip.conf
    echo "threewaycalling=no" >> /etc/asterisk/sip.conf
    echo "callwaiting=no" >> /etc/asterisk/sip.conf
    echo "hasmanager=no" >> /etc/asterisk/sip.conf
    echo "hasagent=yes" >> /etc/asterisk/sip.conf
    echo "hassip=yes" >> /etc/asterisk/sip.conf
    echo "hasiax=no" >> /etc/asterisk/sip.conf
    echo "canreinvite=no" >> /etc/asterisk/sip.conf
    echo "dtmfmode=rfc2833" >> /etc/asterisk/sip.conf
    echo "insecure=port,invite" >> /etc/asterisk/sip.conf
    echo "autoprov=no" >> /etc/asterisk/sip.conf
    echo "disallow=all" >> /etc/asterisk/sip.conf
    echo "allow=ulaw" >> /etc/asterisk/sip.conf
    echo "allow=alaw" >> /etc/asterisk/sip.conf
    echo ";allow=G726" >> /etc/asterisk/sip.conf
    echo ";allow=G729" >> /etc/asterisk/sip.conf
    echo ";allow=G723.1" >> /etc/asterisk/sip.conf
    echo "qualify=yes ; Qualify peer is no more than 2000 ms away" >> /etc/asterisk/sip.conf
    echo "nat=${SPA3102_NAT} ; located in the same LAN as Asterisk" >> /etc/asterisk/sip.conf
    
    echo "" >> /etc/asterisk/sip.conf
    echo "[spa3102-pstn]" >> /etc/asterisk/sip.conf
    echo "username=${SPA3102_PSTN_USERNAME}" >> /etc/asterisk/sip.conf
    echo "host=${SPA3102_IP_ADDRESS}" >> /etc/asterisk/sip.conf
    echo "port=${SPA3102_PSTN_SIP_PORT}" >> /etc/asterisk/sip.conf
    echo "secret=${SPA3102_PSTN_PASSWD}" >> /etc/asterisk/sip.conf
    echo "call-limit=1" >> /etc/asterisk/sip.conf
    echo "type=peer" >> /etc/asterisk/sip.conf
    echo "registersip=no" >> /etc/asterisk/sip.conf
    echo "context=spa3102-pstn ; the internal context controls what we can do" >> /etc/asterisk/sip.conf
    echo ";;cid_number=${SPA3102_PSTN_CID}" >> /etc/asterisk/sip.conf
    echo "hasvoicemail=no" >> /etc/asterisk/sip.conf
    echo "threewaycalling=no" >> /etc/asterisk/sip.conf
    echo "callwaiting=no" >> /etc/asterisk/sip.conf
    echo "hasmanager=no" >> /etc/asterisk/sip.conf
    echo "hasagent=yes" >> /etc/asterisk/sip.conf
    echo "hassip=yes" >> /etc/asterisk/sip.conf
    echo "hasiax=no" >> /etc/asterisk/sip.conf
    echo "canreinvite=no" >> /etc/asterisk/sip.conf
    echo "dtmfmode=rfc2833" >> /etc/asterisk/sip.conf
    echo "insecure=port,invite" >> /etc/asterisk/sip.conf
    echo "disallow=all" >> /etc/asterisk/sip.conf
    echo "allow=ulaw" >> /etc/asterisk/sip.conf
    echo "allow=alaw" >> /etc/asterisk/sip.conf
    echo ";allow=G726" >> /etc/asterisk/sip.conf
    echo ";allow=G729" >> /etc/asterisk/sip.conf
    echo ";allow=G723.1" >> /etc/asterisk/sip.conf
    echo "qualify=yes ; Qualify peer is no more than 2000 ms away" >> /etc/asterisk/sip.conf
    echo "nat=${SPA3102_NAT} ; located in the same LAN as Asterisk" >> /etc/asterisk/sip.conf
    
    # /etc/asterisk/extensions.conf
    if [ ! -f /etc/asterisk/extensions.conf.orig ]; then
        cp /etc/asterisk/extensions.conf /etc/asterisk/extensions.conf.orig
    fi
    
    echo "" >> /etc/asterisk/extensions.conf
    echo "[spa3102-line1]" >> /etc/asterisk/extensions.conf
    echo ";; area dial plan" >> /etc/asterisk/extensions.conf
    echo "exten => ${AREA_DIAL_PLAN},1,Dial(SIP/\${EXTEN}@spa3102-pstn,60,)" >> /etc/asterisk/extensions.conf
    echo ";; toll free numbers" >> /etc/asterisk/extensions.conf
    echo ";;exten => _1800XXXXXXX,1,Dial(SIP/\${EXTEN}@spa3102-pstn,60,)" >> /etc/asterisk/extensions.conf
    echo ";;exten => _1888XXXXXXX,1,Dial(SIP/\${EXTEN}@spa3102-pstn,60,)" >> /etc/asterisk/extensions.conf
    echo ";;exten => _1866XXXXXXX,1,Dial(SIP/\${EXTEN}@spa3102-pstn,60,)" >> /etc/asterisk/extensions.conf
    
    echo "" >> /etc/asterisk/extensions.conf
    echo "[spa3102-pstn]" >> /etc/asterisk/extensions.conf
    echo ";; extension 123 is for incoming PSTN calls" >> /etc/asterisk/extensions.conf
    echo ";; in the SPA3102 PSTN tab dialplan S0<:123@192.168.0.2>" >> /etc/asterisk/extensions.conf
    echo ";; causes the incoming PSTN to VoIP calls to be redirected" >> /etc/asterisk/extensions.conf
    echo ";; to this extension" >> /etc/asterisk/extensions.conf
    echo "exten => ${SPA3102_PSTN_CID},1,NoOP(\${CALLERID}) ; show the caller ID info in the console" >> /etc/asterisk/extensions.conf
    echo "exten => ${SPA3102_PSTN_CID},n,Ringing()" >> /etc/asterisk/extensions.conf
    echo "exten => ${SPA3102_PSTN_CID},n,Answer()" >> /etc/asterisk/extensions.conf
    echo "exten => ${SPA3102_PSTN_CID},n,Playback(silence/1)" >> /etc/asterisk/extensions.conf
    echo "exten => ${SPA3102_PSTN_CID},n,Playback(pls-wait-connect-call)" >> /etc/asterisk/extensions.conf
    echo "exten => ${SPA3102_PSTN_CID},n,Wait(3)" >> /etc/asterisk/extensions.conf
    echo ";; attempt to connect the call to the FXS (Line1) port" >> /etc/asterisk/extensions.conf
    echo "exten => ${SPA3102_PSTN_CID},n,Dial(SIP/spa3102-line1,60)" >> /etc/asterisk/extensions.conf
    echo "exten => ${SPA3102_PSTN_CID},n,Congestion" >> /etc/asterisk/extensions.conf
    
    # Add the trunks replacing demo
    sed -e "s/^include => demo/include => spa3102-line1\ninclude => spa3102-pstn/" -i /etc/asterisk/extensions.conf

    # Restart asterisk
    asterisk -x "core restart now"
    
    return 0
}

do_chan_dongle_config()
{
    
}

calc_wt_size

whiptail --yesno "Configure Linksys SPA3102?" 20 60 2
if [ $? -eq 0 ]; then # yes
    do_spa3102_config
fi

whiptail --yesno "Configure chan_dongle?" 20 60 2
if [ $? -eq 0 ]; then # yes
    do_chan_dongle_config
fi
