#!/bin/bash
# Sources:
#    http://www.fredshack.com/docs/linksys_3102.html
#    http://forums.digium.com/viewtopic.php?t=72277
#    http://forum.voxilla.com/threads/starter-spa3102-asterisk-setup.9352/

calc_wt_size() {
    # NOTE: it's tempting to redirect stderr to /dev/null, so supress error 
    # output from tput. However in this case, tput detects neither stdout or 
    # stderr is a tty and so only gives default 80, 24 values
    WT_HEIGHT=17
    WT_WIDTH=$(tput cols)

    if [ -z "$WT_WIDTH" ] || [ "$WT_WIDTH" -lt 60 ]; then
        WT_WIDTH=80
    fi
    if [ "$WT_WIDTH" -gt 178 ]; then
        WT_WIDTH=120
    fi
    WT_MENU_HEIGHT=$(($WT_HEIGHT-7))
}

do_spa3102_cofig() {
    if [ ! -f /etc/asterisk/sip.conf.orig ]; then
        cp /etc/asterisk/sip.conf /etc/asterisk/sip.conf.orig
    fi
    
    echo "" >> /etc/asterisk/sip.conf
    echo "[spa3102-line1]" >> /etc/asterisk/sip.conf
    echo "username=124" >> /etc/asterisk/sip.conf
    echo "secret=fxo" >> /etc/asterisk/sip.conf
    echo "call-limit=1" >> /etc/asterisk/sip.conf
    echo "type=peer" >> /etc/asterisk/sip.conf
    echo "registersip=no" >> /etc/asterisk/sip.conf
    echo "host=dynamic ; This device registers with us" >> /etc/asterisk/sip.conf
    echo "context=spa3102-line1 ; the internal context controls what we can do" >> /etc/asterisk/sip.conf
    echo "cid_number=124" >> /etc/asterisk/sip.conf
    echo "hasvoicemail=no" >> /etc/asterisk/sip.conf
    echo "threewaycalling=no" >> /etc/asterisk/sip.conf
    echo "callwaiting=no" >> /etc/asterisk/sip.conf
    echo "hasmanager=no" >> /etc/asterisk/sip.conf
    echo "hasagent=yes" >> /etc/asterisk/sip.conf
    echo "hassip=yes" >> /etc/asterisk/sip.conf
    echo "hasiax=no" >> /etc/asterisk/sip.conf
    echo "canreinvite=no" >> /etc/asterisk/sip.conf
    echo "dtmfmode=rfc2833" >> /etc/asterisk/sip.conf
    echo "insecure=no" >> /etc/asterisk/sip.conf
    echo "autoprov=no" >> /etc/asterisk/sip.conf
    echo "disallow=all" >> /etc/asterisk/sip.conf
    echo "allow=alaw" >> /etc/asterisk/sip.conf
    echo "allow=ulaw" >> /etc/asterisk/sip.conf
    echo "qualify=yes ; Qualify peer is no more than 2000 ms away" >> /etc/asterisk/sip.conf
    echo "nat=no ; located in the same LAN as Asterisk" >> /etc/asterisk/sip.conf
    
    echo "" >> /etc/asterisk/sip.conf
    echo "[spa3102-pstn]" >> /etc/asterisk/sip.conf
    echo "username=124" >> /etc/asterisk/sip.conf
    echo "host=192.168.0.1" >> /etc/asterisk/sip.conf
    echo "port=5061" >> /etc/asterisk/sip.conf
    echo "secret=fxo" >> /etc/asterisk/sip.conf
    echo "call-limit=1" >> /etc/asterisk/sip.conf
    echo "type=peer" >> /etc/asterisk/sip.conf
    echo "registersip=no" >> /etc/asterisk/sip.conf
    echo "host=dynamic ; This device registers with us" >> /etc/asterisk/sip.conf
    echo "context=spa3102-pstn ; the internal context controls what we can do" >> /etc/asterisk/sip.conf
    echo "cid_number=124" >> /etc/asterisk/sip.conf
    echo "hasvoicemail=no" >> /etc/asterisk/sip.conf
    echo "threewaycalling=no" >> /etc/asterisk/sip.conf
    echo "callwaiting=no" >> /etc/asterisk/sip.conf
    echo "hasmanager=no" >> /etc/asterisk/sip.conf
    echo "hasagent=yes" >> /etc/asterisk/sip.conf
    echo "hassip=yes" >> /etc/asterisk/sip.conf
    echo "hasiax=no" >> /etc/asterisk/sip.conf
    echo "canreinvite=no" >> /etc/asterisk/sip.conf
    echo "dtmfmode=rfc2833" >> /etc/asterisk/sip.conf
    echo "insecure=very" >> /etc/asterisk/sip.conf
    echo "disallow=all" >> /etc/asterisk/sip.conf
    echo "allow=alaw" >> /etc/asterisk/sip.conf
    echo "allow=ulaw" >> /etc/asterisk/sip.conf

    # /etc/asterisk/extensions.conf
    if [ ! -f /etc/asterisk/extensions.conf.orig ]; then
        cp /etc/asterisk/extensions.conf /etc/asterisk/extensions.conf.orig
    fi
    
    echo "" >> /etc/asterisk/extensions.conf
    echo "[spa3102-line1]" >> /etc/asterisk/extensions.conf
    echo ";; my area uses 10 digit dialing, hence the 10 X's" >> /etc/asterisk/extensions.conf
    echo ";; change the following line to suit your needs" >> /etc/asterisk/extensions.conf
    echo "exten => _XXXXXXXXXX,1,Dial(SIP/\${EXTEN}@spa3102-pstn,60,)" >> /etc/asterisk/extensions.conf
    echo ";; toll free numbers" >> /etc/asterisk/extensions.conf
    echo "exten => _1800XXXXXXX,1,Dial(SIP/\${EXTEN}@spa3102-pstn,60,)" >> /etc/asterisk/extensions.conf
    echo "exten => _1888XXXXXXX,1,Dial(SIP/\${EXTEN}@spa3102-pstn,60,)" >> /etc/asterisk/extensions.conf
    echo "exten => _1866XXXXXXX,1,Dial(SIP/\${EXTEN}@spa3102-pstn,60,)" >> /etc/asterisk/extensions.conf
    
    echo "" >> /etc/asterisk/extensions.conf
    echo "[spa3102-pstn]" >> /etc/asterisk/extensions.conf
    echo ";; extension 123 is for incoming PSTN calls" >> /etc/a" >> /etc/asterisk/extensions.confsterisk/extensions.conf
    echo ";; in the SPA3102 PSTN tab dialplan S0<:123@192.168.0.2>" >> /etc/asterisk/extensions.conf
    echo ";; causes the incoming PSTN to VoIP calls to be redirected" >> /etc/asterisk/extensions.conf
    echo ";; to this extension" >> /etc/asterisk/extensions.conf
    echo "exten => 123,1,NoOP(\${CALLERID}) ; show the caller ID info in the console" >> /etc/asterisk/extensions.conf
    echo "exten => 123,n,Ringing()" >> /etc/asterisk/extensions.conf
    echo "exten => 123,n,Answer()" >> /etc/asterisk/extensions.conf
    echo "exten => 123,n,Playback(silence/1)" >> /etc/asterisk/extensions.conf
    echo "exten => 123,n,Playback(pls-wait-connect-call)" >> /etc/asterisk/extensions.conf
    echo "exten => 123,n,Wait(3)" >> /etc/asterisk/extensions.conf
    echo ";; attempt to connect the call to the FXS (Line1) port" >> /etc/asterisk/extensions.conf
    echo "exten => 123,n,Dial(SIP/spa3102-line1,60)" >> /etc/asterisk/extensions.conf
    echo "exten => 123,n,Congestion" >> /etc/asterisk/extensions.conf
}

calc_wt_size

do_spa3102_config
