#!/bin/bash
# https://wiki.asterisk.org/wiki/display/AST/System+Libraries

#ASTERISK_VERSION='11.6-cert11'
ASTERISK_VERSION='11.18.0'

do_install_build_dependencies()
{
    # autoconf needed for bootstrap.sh
    apt-get install -y build-essential autoconf libsqlite3-dev libxml2-dev uuid-dev libncurses5-dev libncursesw5-dev libiksemel-dev libssl-dev libeditline-dev libedit-dev curl libcurl4-gnutls-dev
}

# Get Asterisk sources
do_download_asterisk()
{
    cd /usr/src
    #wget http://downloads.asterisk.org/pub/telephony/certified-asterisk/certified-asterisk-${ASTERISK_VERSION}.tar.gz
    wget http://downloads.asterisk.org/pub/telephony/asterisk/asterisk-${ASTERISK_VERSION}.tar.gz
    #tar -zxf certified-asterisk-${ASTERISK_VERSION}.tar.gz
    #rm certified-asterisk-${ASTERISK_VERSION}.tar.gz
    #mv certified-asterisk-${ASTERISK_VERSION} asterisk-${ASTERISK_VERSION}
    tar -zxf asterisk-${ASTERISK_VERSION}
    cd /usr/src/asterisk-${ASTERISK_VERSION}
    #./contrib/scripts/install_prereq install
    ./bootstrap.sh
}

do_build_chan_dongle()
{
    cd /usr/src
    wget https://github.com/jstasiak/asterisk-chan-dongle/archive/asterisk11.tar.gz -O asterisk-chan-dongle-asterisk11.tar.gz
    tar -zxf asterisk-chan-dongle-asterisk11.tar.gz
    cd /usr/src/asterisk-chan-dongle-asterisk11

    aclocal && autoconf && automake -a
    ./configure --with-asterisk="/usr/src/asterisk-${ASTERISK_VERSION}/include"
    make
}

# Build Asterisk
do_build_asterisk()
{
    cd /usr/src/asterisk-${ASTERISK_VERSION}
    
    ./configure --disable-xmldoc
    make menuselect
    make
    make install
    #checkinstall -D --install=no --pkgversion=${VERSION} \
    #    --requires="libc6, libcap2, libedit2, libgcc1, libpopt0, libsqlite3-0, libssl1.0.0, libstdc++6, libtinfo5, libxml2, libiksemel3, sox, uuid"

    #make samples
    #make config
}

do_set_permissions()
{
    adduser asterisk --disabled-password --home=/var/lib/asterisk --no-create-home --gecos "asterisk PBX user"
    #adduser www-data asterisk

    #MODIFYING ASTERISK
    ln -s /var/lib/asterisk/moh /var/lib/asterisk/mohmp3   
    cp /etc/asterisk/asterisk.conf /etc/asterisk/asterisk.conf.`date +%Y.%m.%d.%Hh.%mm`
    sed -i "s/\(astrundir *=> *\)\(.*\)/\1\/var\/run\/asterisk/" /etc/asterisk/asterisk.conf
    sed -i '1 {s/\<sh\>/bash/}' /usr/sbin/safe_asterisk
    sed -i "s,SAFE_AST_BACKGROUND=0,SAFE_AST_BACKGROUND=1," /usr/sbin/safe_asterisk
    chown asterisk:asterisk -R /var/run/asterisk
    chown asterisk:asterisk -R /etc/asterisk
    chown asterisk:asterisk -R /var/lib/asterisk
    chown asterisk:asterisk -R /var/log/asterisk
    chown asterisk:asterisk -R /var/spool/asterisk
    chmod 770 /etc/asterisk/
    chmod 770 /var/lib/asterisk/
}

# Had some troubles with date on my tests so...
if which ntptime >/dev/null; then
    ntptime -s time.nist.gov
fi

do_install_build_dependencies
do_download_asterisk
do_build_asterisk
