#!/bin/bash
#
# Asterisk for raspberry
# Resources:
#    http://matthewjordan.net/2013/09/02/asterisk-12-on-a-raspberry-pi/
#    http://community.freepbx.org/t/debian-wheezy-freepbx-12-asterisk-13-1-0-how-to-mostly-working-with-warnings/26845

ASTERISK_VERSION='11'
FREEPBX_VERSION='12.0'

if [ ! -f /etc/network/interfaces ]; then
    echo "auto lo" > /etc/network/interfaces
    echo "iface lo inet loopback" >> /etc/network/interfaces
    echo "" >> /etc/network/interfaces
    echo "auto eth0" >> /etc/network/interfaces
    echo "iface eth0 inet dhcp" >> /etc/network/interfaces
    
    ifconfig lo 127.0.0.1 netmask 255.0.0.0 up
fi

# Required packages to build Asterisk
apt-get install -y git-core

# Installl Asterisk Dependencies
apt-get install -y build-essential libsqlite3-dev libxml2-dev libncurses5-dev libncursesw5-dev libiksemel-dev libssl-dev libeditline-dev libedit-dev curl libcurl4-gnutls-dev

# Since this is Asterisk 12, however, I’ll want a few other things as well. 
# The CHANGES and UPGRADE.txt file tell you the additional dependencies
# let’s got those as well:
apt-get install -y libjansson4 libjansson-dev libuuid1 uuid-dev libxslt1-dev liburiparser-dev liburiparser1

cd /usr/src

git clone -b ${ASTERISK_VERSION} http://gerrit.asterisk.org/asterisk asterisk-${ASTERISK_VERSION}

if [ $ASTERISK_VERSION  -gt 11 ]; then
    git clone https://github.com/asterisk/pjproject pjproject
    
    cd /usr/src/pjproject
    
    #  I don’t have libsrtp installed and I’m not going to use SRTP in Asterisk, so I 
    # can ignore that. I also don’t have libspeex installed, and I don’t really care 
    # about using libspeex in Asterisk either. The same goes for the GSM library. So, 
    # in the end I ended up with the following
    ./configure --prefix=/usr --enable-shared --disable-sound --disable-video --disable-resample
    make dep
    make
    make install
fi

cd /usr/src/asterisk-${ASTERISK_VERSION}
if [ $ASTERISK_VERSION  -gt 11 ]; then
    ./configure --with-pjproject
else
    ./configure
fi

make menuselect

make
make install

cp /usr/src/asterisk-${ASTERISK_VERSION}/contrib/init.d/rc.debian.asterisk /etc/init.d/asterisk

sed -e 's/__ASTERISK_SBIN_DIR__/\/usr\/sbin/g' -e 's/__ASTERISK_VARRUN_DIR__/\/var\/run\/asterisk\//g' -e 's/__ASTERISK_ETC_DIR__/\/etc\/asterisk\//g' -i /etc/init.d/asterisk
sed -e 's/\/bin\/sh/\/bin\/bash/g' -i /etc/init.d/asterisk
sed -e 's/set -e/set -e\nsource \/etc\/profile/g' -i /etc/init.d/asterisk
#set up websockets for webrtc
sed -e 's/;enabled/enabled/g' -i /etc/asterisk/http.conf
sed -e 's/;bindport/bindport/g' -i /etc/asterisk/http.conf
sed -e 's/;\Wicesupport/icesupport/g' -i /etc/asterisk/rtp.conf
sed -e 's/;\Wstunaddr=/stunaddr=stun.l.google.com:19302/g' -i /etc/asterisk/rtp.conf
ed -e 's/transport=udp/transport=udp,ws/g' -i /etc/asterisk/sip.conf
#prep asterisk for multiple users
touch /etc/asterisk/userconf_extensions.conf
echo "#include /etc/asterisk/userconf_extensions.conf" >> /etc/asterisk/extensions.conf
touch /etc/asterisk/userconf_sip.conf
echo "#include /etc/asterisk/userconf_sip.conf" >> /etc/asterisk/sip.conf
touch /etc/asterisk/userconf_iax.conf
echo "#include /etc/asterisk/userconf_iax.conf" >> /etc/asterisk/iax.conf
touch /etc/asterisk/userconf_voicemail.conf
echo "#include /etc/asterisk/userconf_voicemail.conf" >> /etc/asterisk/voicemail.conf
touch /etc/asterisk/userconf_musiconhold.conf
echo "#include /etc/asterisk/userconf_musiconhold.conf" >> /etc/asterisk/musiconhold.conf
sed -e 's/;\[files\]/\[files\]/g' -i /etc/asterisk/asterisk.conf
sed -e 's/;astctlpermissions = 0660/astctlpermissions = 0770/g' -i /etc/asterisk/asterisk.conf 
sed -e 's/;astctlgroup = apache/astctlgroup = asterisk/g' -i /etc/asterisk/asterisk.conf
sed -e 's/;verbose/verbose/g' -i /etc/asterisk/asterisk.conf

update-rc.d asterisk defaults
service asterisk start

make samples
make progdocs

# FreePBX
apt-get install -y --fix-missing mysql-server
# if it fails... in my case it fails....

apt-get install -y mysql-client
apt-get install -y apache2
apt-get install -y php5 libapache2-mod-php5 php-pear php-db php5-mysql 

mysql -uroot -praspberry -e "CREATE DATABASE asterisk;"

cd /usr/src
git clone http://git.freepbx.org/scm/freepbx/framework.git freepbx-framework
cd /usr/src/freepbx-framework
git checkout release/${FREEPBX_VERSION}
adduser asterisk --disabled-password --gecos "Asterisk User"
chown asterisk. /var/run/asterisk
chown -R asterisk. /etc/asterisk
chown -R asterisk. /var/{lib,log,spool}/asterisk
chown -R asterisk. /usr/lib/asterisk
chown -R asterisk. /var/www/
sed -i 's/\(^upload_max_filesize = \).*/\1120M/' /etc/php5/apache2/php.ini
cp /etc/apache2/apache2.conf /etc/apache2/apache2.conf_orig
sed -i 's/^\(User\|Group\).*/\1 asterisk/' /etc/apache2/apache2.conf
sed -i 's/AllowOverride None/AllowOverride All/' /etc/apache2/sites-available/default
/etc/init.d/apache2 restart

cd /usr/src/freepbx-framework
./install_amp --installdb
./install_amp --update-links
amportal chown
amportal a ma installall
amportal a ma download manager
amportal a ma install manager
amportal a ma installall
amportal chown
amportal a ma refreshsignatures
amportal a reload
ln -s /var/lib/asterisk/moh /var/lib/asterisk/mohmp3
amportal restart


rm /var/www/index.html

#
# Chan Dongle
#
# Official repository: 
#    https://github.com/bg111/asterisk-chan-dongle

apt-get install -y automake

cd /usr/src

if [ $ASTERISK_VERSION -eq 10 ]; then
    git clone -b asterisk10 https://github.com/jstasiak/asterisk-chan-dongle.git asterisk-chan-dongle
elif [ $ASTERISK_VERSION -eq 11 ]; then
    git clone -b asterisk11 https://github.com/jstasiak/asterisk-chan-dongle.git asterisk-chan-dongle
elif [ $ASTERISK_VERSION -eq 12 ]; then
    git clone https://github.com/superles/chan-dongle-asterisk12.git asterisk-chan-dongle
else
    echo "chan_dongle is not available for the selected Asterisk version"
fi

cd /usr/src/asterisk-chan-dongle
aclocal && autoconf && automake -a
./configure –-with-asterisk="/usr/src/asterisk-${ASTERISK_VERSION}/include"
make
make install

cp /usr/src/asterisk-chan-dongle/etc/dongle.conf /etc/asterisk/dongle.conf
