#!/bin/bash
#
# Asterisk for raspberry
# Resources:
#    http://matthewjordan.net/2013/09/02/asterisk-12-on-a-raspberry-pi/

ASTERISK_VERSION='11'

# Required packages to build Asterisk
apt-get install -y git-core

# Installl Asterisk Dependencies
apt-get install -y build-essential libsqlite3-dev libxml2-dev libncurses5-dev libncursesw5-dev libiksemel-dev libssl-dev libeditline-dev libedit-dev curl libcurl4-gnutls-dev

# Since this is Asterisk 12, however, I’ll want a few other things as well. 
# The CHANGES and UPGRADE.txt file tell you the additional dependencies
# let’s got those as well:
apt-get install -y libjansson4 libjansson-dev libuuid1 uuid-dev libxslt1-dev liburiparser-dev liburiparser1

cd /usr/src

git clone -b ${ASTERISK_VERSION} http://gerrit.asterisk.org/asterisk asterisk-${ASTERISK_VERSION}

if [ $ASTERISK_VERSION  -gt 11 ]; then
    git clone https://github.com/asterisk/pjproject pjproject
    
    cd /usr/src/pjproject
    
    #  I don’t have libsrtp installed and I’m not going to use SRTP in Asterisk, so I 
    # can ignore that. I also don’t have libspeex installed, and I don’t really care 
    # about using libspeex in Asterisk either. The same goes for the GSM library. So, 
    # in the end I ended up with the following
    ./configure --prefix=/usr --enable-shared --disable-sound --disable-video --disable-resample
    make dep
    make
    make install
fi

cd /usr/src/asterisk-${ASTERISK_VERSION}
if [ $ASTERISK_VERSION  -gt 11 ]; then
    ./configure --with-pjproject
else
    ./configure
fi

make menuselect

make
make install

make samples
make progdocs

#
# Chan Dongle
#
# Official repository: 
#    https://github.com/bg111/asterisk-chan-dongle

apt-get install -y automake

cd /usr/src

if [ $ASTERISK_VERSION -eq 10 ]; then
    git clone -b asterisk10 https://github.com/jstasiak/asterisk-chan-dongle.git asterisk-chan-dongle
elif [ $ASTERISK_VERSION -eq 11 ]; then
    git clone -b asterisk11 https://github.com/jstasiak/asterisk-chan-dongle.git asterisk-chan-dongle
elif [ $ASTERISK_VERSION -eq 12 ]; then
    git clone https://github.com/superles/chan-dongle-asterisk12.git asterisk-chan-dongle
else
    echo "chan_dongle is not available for the selected Asterisk version"
fi

cd /usr/src/asterisk-chan-dongle
aclocal && autoconf && automake -a
./configure
make
make install
