#!/bin/bash
BACKUP_PATH='/root'
IMAGE_FREESPACE=64

ROOTFS_SIZE=`df -B MB | grep 'rootfs' | awk '{print $3}' | awk -F "MB" '{print $1}'`
if [ -z ${ROOTFS_SIZE} ]; then
    echo "Unable to get root filesystem size."
    exit 1
fi

BOOTFS_SIZE=`df -B MB | grep '/dev/mmcblk0p1' | awk '{print $2}' | awk -F "MB" '{print $1}'`
if [ -z ${BOOTFS_SIZE} ]; then
    echo "Unable to get boot filesystem size."
    exit 1
fi

if [ $IMAGE_FREESPACE -lt 8 ]; then
    $IMAGE_FREESPACE=8
fi

IMAGE_SIZE=$(expr ${ROOTFS_SIZE} + ${BOOTFS_SIZE} + ${IMAGE_FREESPACE} )

echo "Creating image file..."
IMAGE_FILE="${BACKUP_PATH}/rpi_backup.img"
dd if=/dev/zero of=${IMAGE_FILE} bs=1M count=${IMAGE_SIZE}

parted ${IMAGE_FILE} --script -- mklabel msdos
parted ${IMAGE_FILE} --script -- mkpart primary fat32 0 64
parted ${IMAGE_FILE} --script -- mkpart primary ext4 64 -1
        
echo "Done."
