#!/bin/bash
#==================================================#
# Reduce RAM usage                                 #
#==================================================#

if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root" 1>&2
    exit 1
fi

# No monitor so make GPU memory as low as possible
if [ -e /boot/start_cd.elf ]; then
    grep -q '^gpu_mem' /boot/config.txt
    if [ $? -eq 0 ]; then
        sed -e 's/^gpu_mem=.*$/gpu_mem=16/' -i /boot/config.txt
    else
        echo "gpu_mem=$amount" >> /boot/config.txt
    fi
fi

# Disable TTYs to save some RAM
sed -i '/[2-6]:23:respawn:\/sbin\/getty 38400 tty[2-6]/s%^%#%g' /etc/inittab
