#!/bin/bash

ASTERISK_USERS_CONF_USERBASE=6000
CURRENT_EXTENSION_NUM=${ASTERISK_USERS_CONF_USERBASE}
CONFIGURED_EXTENSIONS=()

calc_wt_size() {
    # NOTE: it's tempting to redirect stderr to /dev/null, so supress error 
    # output from tput. However in this case, tput detects neither stdout or 
    # stderr is a tty and so only gives default 80, 24 values
    WT_HEIGHT=17
    WT_WIDTH=$(tput cols)

    if [ -z "$WT_WIDTH" ] || [ "$WT_WIDTH" -lt 60 ]; then
        WT_WIDTH=80
    fi
    if [ "$WT_WIDTH" -gt 178 ]; then
        WT_WIDTH=120
    fi
    WT_MENU_HEIGHT=$(($WT_HEIGHT-7))
}

do_set_userbase()
{
    local userbase=${ASTERISK_USERS_CONF_USERBASE}
    
    while true; do
        userbaser=$(whiptail --inputbox "Introduzca la primera extensión para los usuarios" 20 60 "${ASTERISK_USERS_CONF_USERBASE}" 3>&1 1>&2 2>&3)
        if [ $? -eq 0 ]; then
            if [[ $userbase =~ ^-?[0-9]+$ ]]; then
                ASTERISK_USERS_CONF_USERBASE=${userbase}
                CURRENT_EXTENSION_NUM=${userbase}
                return 0
            else
                whiptail --msgbox "La extensión debe ser un valor numérico." 20 60 1
            fi
        else
            return 1
        fi
    done
}

do_add_user() {
    local extension_fullname=''
    local extension_email=''
    local extension_password=''
    local extension_cid_number=''
    
    extension_cid_number=${CURRENT_EXTENSION_NUM}
    
    extension_password=$(whiptail --passwordbox "Introduzca la contraseña del usuario" 20 60 "" 3>&1 1>&2 2>&3)
    if [ $? -ne 0 ]; then
        return 1
    fi
    
    extension_fullname=$(whiptail --inputbox "Introduzca el nombre completo del usuario" 20 60 "" 3>&1 1>&2 2>&3)
    if [ $? -ne 0 ]; then
        return 1
    fi
    
    extension_email=$(whiptail --inputbox "Introduzca el correo electrónico del usuario" 20 60 "" 3>&1 1>&2 2>&3)
    if [ $? -ne 0 ]; then
        return 1
    fi
    
    echo ""  >> /etc/asterisk/users.conf
    echo "[${extension_num]" >> /etc/asterisk/users.conf
    echo "host=dymanic" >> /etc/asterisk/users.conf
    echo "secret=${extension_password}" >> /etc/asterisk/users.conf
    echo "fullname=${extension_fullname}" >> /etc/asterisk/users.conf
    echo "email=${extension_email}" >> /etc/asterisk/users.conf
    echo "cid_number=${extension_cid_number}" >> /etc/asterisk/users.conf
    
    CONFIGURED_EXTENSIONS+=( "SIP/${CURRENT_EXTENSION_NUM}" )
    ((CURRENT_EXTENSION_NUM=CURRENT_EXTENSION_NUM+1))
}

do_movistar_ftth() {
    local sip_extensions=$( IFS=$'&'; echo "${CONFIGURED_EXTENSIONS[*]}" )
    
    PHONENUMBER=$(whiptail --inputbox "Introduzca su número de teléfono" 20 60 "$CURRENT_HOSTNAME" 3>&1 1>&2 2>&3)
    if [ $? -ne 0 ]; then
        return 1
    fi
    
    # Configuracion para Movistar por SIP
    echo "" >> /etc/asterisk/sip.conf
    echo "[Movistar](!)" >> /etc/asterisk/sip.conf
    echo "type=peer" >> /etc/asterisk/sip.conf
    #echo "callerid=${PHONENUMBER}" >> /etc/asterisk/sip.conf
    #echo "host=telefonica.net" >> /etc/asterisk/sip.conf
    #echo "port=5060" >> /etc/asterisk/sip.conf
    #echo "from-domain=telefonica.net" >> /etc/asterisk/sip.conf
    #echo "fromuser=${PHONENUMBER}" >> /etc/asterisk/sip.conf
    echo "secret=${PHONENUMBER}" >> /etc/asterisk/sip.conf
    echo "dtmfmode=auto" >> /etc/asterisk/sip.conf
    echo "insecure=port,invite" >> /etc/asterisk/sip.conf
    echo "outboundproxy=10.31.255.134:5070" >> /etc/asterisk/sip.conf
    echo "nat=force_rport,comedia" >> /etc/asterisk/sip.conf
    #echo "trustrpid=yes" >> /etc/asterisk/sip.conf
    #echo "sendrpid=yes" >> /etc/asterisk/sip.conf
    echo "disallow=all" >> /etc/asterisk/sip.conf
    echo "allow=ulaw" >> /etc/asterisk/sip.conf
    echo "allow=alaw" >> /etc/asterisk/sip.conf
    #echo "context=from-movistar" >> /etc/asterisk/sip.conf
    
    echo "" >> /etc/asterisk/sip.conf
    echo "[MovistarOut](Movistar)" >> /etc/asterisk/sip.conf
    echo "host=telefonica.net" >> /etc/asterisk/sip.conf
    echo "from-domain=telefonica.net" >> /etc/asterisk/sip.conf
    echo "fromuser=${PHONENUMBER}" >> /etc/asterisk/sip.conf
    
    echo "" >> /etc/asterisk/sip.conf
    echo "[MovistarIn](Movistar)" >> /etc/asterisk/sip.conf
    echo "context=from-movistar" >> /etc/asterisk/sip.conf
    echo "defaultuser=${PHONENUMBER}" >> /etc/asterisk/sip.conf
    echo "host=10.31.255.134" >> /etc/asterisk/sip.conf
    echo "port=5060" >> /etc/asterisk/sip.conf
    echo "qualify=no" >> /etc/asterisk/sip.conf
    echo "trustpid=yes" >> /etc/asterisk/sip.conf
    
    sed -e "s|^;register => 2345:password@sip_proxy/1234|;register => 2345:password@sip_proxy/1234\nregister => ${PHONENUMBER}@telefonica.net:${PHONENUMBER}@10.31.255.134:5070|" -i /etc/asterisk/sip.conf

    echo "" >> /etc/asterisk/extensions.conf
    echo "[outbound-movistar]" >> /etc/asterisk/extensions.conf
    echo "exten => _X.,1,Dial(SIP/MovistarOut/\${EXTEN})" >> /etc/asterisk/extensions.conf
    
    echo "" >> /etc/asterisk/extensions.conf
    echo "[from-movistar]" >> /etc/asterisk/extensions.conf
    echo "exten => s,1,Dial(${sip_extensions})"
    
    sed -e "s|^include => demo|include => outbound-movistar|" -i /etc/asterisk/extensions.conf
}

calc_wt_size

do_set_userbase

while true; do
    do_add_user

    whiptail --yesno "¿Desea agregar otro usuario?" 20 60 2 --yes-button Si --no-button No
    if [ $? -eq 1 ]; then
        break
    fi
done

do_movistar_ftth
